# Generated by Django 5.2.8 on 2025-11-13 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedrockModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable model name', max_length=255, unique=True)),
                ('model_id', models.CharField(help_text='AWS Bedrock model ID (e.g., anthropic.claude-3-sonnet-20240229-v1:0)', max_length=255, unique=True)),
                ('region', models.CharField(default='us-east-1', help_text='AWS region for the model', max_length=50)),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum tokens in response', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)])),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature for generation (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('top_p', models.FloatField(default=0.9, help_text='Top-p sampling parameter', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('prompt_template', models.TextField(blank=True, help_text='Default prompt template for this model')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default model')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is active and available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['model_id'], name='invoice_llm_model_i_cb0991_idx'), models.Index(fields=['is_active', 'is_default'], name='invoice_llm_is_acti_9e5705_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=255, unique=True)),
                ('value', models.JSONField(help_text='Configuration value (can be string, number, object, array)')),
                ('description', models.TextField(blank=True, help_text='Description of this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='invoice_llm_key_48c097_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the processed file', max_length=1000)),
                ('method', models.CharField(choices=[('bedrock', 'AWS Bedrock'), ('textract', 'AWS Textract')], help_text='Processing method used', max_length=20)),
                ('model_id', models.CharField(blank=True, help_text='Model ID used (if Bedrock)', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text from the invoice')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the processing')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='invoice_llm_status_bd6ce2_idx'), models.Index(fields=['method'], name='invoice_llm_method_8cac0d_idx'), models.Index(fields=['created_at'], name='invoice_llm_created_81c9ee_idx')],
            },
        ),
    ]
