# Generated by Django 5.2.8 on 2025-11-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrockmodelconfig',
            name='input_token_cost',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Cost per 1K input tokens (e.g., 0.003 for $0.003 per thousand)', max_digits=10),
        ),
        migrations.AddField(
            model_name='bedrockmodelconfig',
            name='output_token_cost',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Cost per 1K output tokens (e.g., 0.015 for $0.015 per thousand)', max_digits=10),
        ),
    ]
