# Generated by Django 5.2.8 on 2025-11-13 23:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('state_code', models.CharField(help_text='US state code (e.g., CA, NY)', max_length=2)),
                ('jurisdiction', models.CharField(blank=True, help_text='Specific jurisdiction if applicable', max_length=255)),
                ('pdf_file', models.FileField(help_text='Uploaded invoice PDF', upload_to='invoices/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='taxright_in_invoice_a8fd67_idx'), models.Index(fields=['status'], name='taxright_in_status_6a6aaf_idx'), models.Index(fields=['date'], name='taxright_in_date_411253_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tax rate as decimal (e.g., 0.0825 for 8.25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_status', models.CharField(choices=[('taxable', 'Taxable'), ('exempt', 'Exempt'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='taxright.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('jurisdiction', models.CharField(blank=True, help_text='County, city, or special district name', max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=4, help_text='Tax rate as decimal (e.g., 0.0825 for 8.25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_date', models.DateField(help_text='Date when this rule becomes effective')),
                ('rule_type', models.CharField(choices=[('state', 'State'), ('county', 'County'), ('city', 'City'), ('special', 'Special District')], default='state', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state_code', 'jurisdiction', '-effective_date'],
                'indexes': [models.Index(fields=['state_code'], name='taxright_ta_state_c_7cb81f_idx'), models.Index(fields=['effective_date'], name='taxright_ta_effecti_a0b7c6_idx')],
                'unique_together': {('state_code', 'jurisdiction', 'effective_date', 'rule_type')},
            },
        ),
        migrations.CreateModel(
            name='TaxDetermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('determination_status', models.CharField(choices=[('verified', 'Verified'), ('discrepancy', 'Discrepancy'), ('error', 'Error')], db_index=True, default='verified', max_length=20)),
                ('expected_tax', models.DecimalField(decimal_places=2, help_text='Expected tax amount based on calculations', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_tax', models.DecimalField(decimal_places=2, help_text='Actual tax amount from invoice', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, help_text='Difference between expected and actual tax (can be negative)', max_digits=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the determination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_determination', to='taxright.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['determination_status'], name='taxright_ta_determi_364ba6_idx')],
            },
        ),
    ]
