# Generated by Django 5.2.8 on 2025-11-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_ocr', '0001_initial'),
        ('taxright', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ocr_error',
            field=models.TextField(blank=True, help_text='Error message if OCR processing failed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_job',
            field=models.ForeignKey(blank=True, help_text='Reference to OCR processing job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoice_ocr.processingjob'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='raw_ocr_data',
            field=models.TextField(blank=True, help_text='Raw JSON response from OCR processing', null=True),
        ),
    ]
