# Generated by Django 5.2.8 on 2025-11-15 04:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxright', '0002_invoice_ocr_error_invoice_ocr_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdetermination',
            name='kb_verification_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata from Bedrock KB verification (KB ID, query details, etc.)'),
        ),
        migrations.CreateModel(
            name='StateKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, help_text='US state code (e.g., CA, NY)', max_length=2, unique=True)),
                ('knowledge_base_id', models.CharField(help_text='AWS Bedrock Knowledge Base ID', max_length=255)),
                ('knowledge_base_name', models.CharField(help_text='Human-readable KB name', max_length=255)),
                ('region', models.CharField(default='us-east-1', help_text='AWS region for the knowledge base', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this KB mapping is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state_code'],
                'indexes': [models.Index(fields=['state_code', 'is_active'], name='taxright_st_state_c_49bdfb_idx')],
            },
        ),
        migrations.CreateModel(
            name='LineItemTaxVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(help_text='Whether the applied tax is correct according to state law')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence score from 0.00 to 1.00', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('reasoning', models.TextField(help_text='Explanation of why the tax is correct or incorrect')),
                ('expected_tax_rate', models.DecimalField(decimal_places=4, help_text='Expected tax rate based on state law (as decimal, e.g., 0.0825 for 8.25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applied_tax_rate', models.DecimalField(decimal_places=4, help_text='Tax rate that was actually applied (as decimal)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('verification_details', models.JSONField(blank=True, default=dict, help_text='Additional verification metadata (KB query details, citations, etc.)')),
                ('verified_at', models.DateTimeField(auto_now_add=True, help_text='When this verification was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_verifications', to='taxright.invoicelineitem')),
            ],
            options={
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['line_item', 'is_correct'], name='taxright_li_line_it_15186e_idx'), models.Index(fields=['verified_at'], name='taxright_li_verifie_3aac31_idx')],
            },
        ),
    ]
