# Generated by Django 5.2.8 on 2025-11-15 05:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxright', '0003_taxdetermination_kb_verification_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax amount from invoice (when tax is shown as total, not per-line-item)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
