# Generated by Django 5.2.8 on 2025-11-15 05:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxright', '0004_invoice_total_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ocr_input_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Cost for OCR input tokens (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_input_tokens',
            field=models.IntegerField(default=0, help_text='Number of input tokens used for OCR processing'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_output_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Cost for OCR output tokens (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_output_tokens',
            field=models.IntegerField(default=0, help_text='Number of output tokens used for OCR processing'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_total_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Total cost for OCR processing (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_verification_input_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Total cost for tax verification input tokens (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_verification_input_tokens',
            field=models.IntegerField(default=0, help_text='Total number of input tokens used for tax verification'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_verification_output_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Total cost for tax verification output tokens (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_verification_output_tokens',
            field=models.IntegerField(default=0, help_text='Total number of output tokens used for tax verification'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_verification_total_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Total cost for tax verification processing (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_llm_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Total LLM cost (OCR + Tax Verification) in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
