# Generated by Django 5.2.8 on 2025-11-15 05:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxright', '0005_invoice_ocr_input_cost_invoice_ocr_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateknowledgebase',
            name='kb_input_token_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Estimated cost per 1K input tokens for KB queries (e.g., 0.003 for $0.003 per thousand). Leave 0.00 to use model default.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stateknowledgebase',
            name='kb_output_token_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Estimated cost per 1K output tokens for KB queries (e.g., 0.015 for $0.015 per thousand). Leave 0.00 to use model default.', max_digits=10),
        ),
    ]
