# Generated by Django 5.2.8 on 2025-11-16 01:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxright', '0007_alter_stateknowledgebase_kb_input_token_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_verification_input_cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_verification_input_tokens',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_verification_output_cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_verification_output_tokens',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_verification_total_cost',
        ),
        migrations.RemoveField(
            model_name='stateknowledgebase',
            name='kb_input_token_cost',
        ),
        migrations.RemoveField(
            model_name='stateknowledgebase',
            name='kb_output_token_cost',
        ),
        migrations.AddField(
            model_name='invoice',
            name='ocr_total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used for OCR processing (input + output)'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='kb_input_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Cost for KB verification input tokens (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='kb_input_tokens',
            field=models.IntegerField(default=0, help_text='Number of input tokens used for KB verification of this line item'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='kb_output_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Cost for KB verification output tokens (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='kb_output_tokens',
            field=models.IntegerField(default=0, help_text='Number of output tokens used for KB verification of this line item'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='kb_total_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Total cost for KB verification of this line item (in USD)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='kb_total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used for KB verification (input + output)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_llm_cost',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), help_text='Total LLM cost (OCR + all line item KB verification costs) in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
