# Generated by Django 5.2.8 on 2025-11-17 15:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxright', '0008_remove_invoice_tax_verification_input_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to entire invoice (e.g., early payment discount, volume discount)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to this specific line item', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
