"""
Django settings for taxjimmy project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import boto3
from botocore.exceptions import ClientError
import json
from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
import multiprocessing


def get_secret(secret_name, region_name):
    # If secret name is empty throw a value error
    if secret_name is None:
        raise ValueError("Secret name is required")
    # Use "us-east-1" if region_name is not specified (i.e., None)
    if region_name is None:
        region_name = "us-east-1"

    # Create a Secrets Manager client
    session = boto3.session.Session()
    client = session.client(
        service_name='secretsmanager',
        region_name=region_name
    )

    try:
        get_secret_value_response = client.get_secret_value(
            SecretId=secret_name
        )
    except ClientError as e:
        # For a list of exceptions thrown, see
        # https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
        raise e

    secret = get_secret_value_response['SecretString']
    return secret

"""Load credentials from environment variables"""
dotenv_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'dev.env')
if not os.path.exists(dotenv_path):
    raise FileNotFoundError(f"Could not find .env file at {dotenv_path}")
load_dotenv(dotenv_path)

if os.getenv('OBJC_DISABLE_INITIALIZE_FORK_SAFETY', None) != 'YES':
    os.environ['OBJC_DISABLE_INITIALIZE_FORK_SAFETY'] = 'YES'

if multiprocessing.get_start_method(allow_none=True) != 'fork':
    multiprocessing.set_start_method('fork', force=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ildsb4%@9jkhafh)qt2!-)r2i8*gw#$pacificx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # This needs to be before allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.amazon_cognito',
    'taxjimmyapp',  # Main app for home page and user portal
    'taxright',  # TaxRight app for invoice processing and tax determinations
    'invoice_llm',  # LLM invoice processing app with Bedrock and Textract
    'debug_toolbar',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django.contrib.postgres',  # For search functionality
    'chroniker',
    'storages',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware", # cognito
]

ROOT_URLCONF = 'taxjimmy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'taxjimmy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# if rds_postgres_secret_key is not None:
rds_postgres_secret_key = os.getenv('RDSPOSTGRESDB_SECRET_KEY', None)
rds_postgres_secret = get_secret(rds_postgres_secret_key, "us-east-1")
if rds_postgres_secret is not None:
    rds_postgres_secret_dict = json.loads(rds_postgres_secret)
    rds_postgres_db_name = rds_postgres_secret_dict.get('dbname', None)
    rds_postgres_db_user = rds_postgres_secret_dict.get('username', None)
    rds_postgres_db_password = rds_postgres_secret_dict.get('password', None)
    rds_postgres_db_host = rds_postgres_secret_dict.get('host', None)
    rds_postgres_db_port = rds_postgres_secret_dict.get('port', None)

if (not rds_postgres_db_name or not rds_postgres_db_user or not rds_postgres_db_password
        or not rds_postgres_db_host or not rds_postgres_db_port):
    raise ValueError("WARNING: RDSPOSTGRESDB_NAME or RDSPOSTGRESDB_USER or RDSPOSTGRESDB_PASSWORD or "
                     "RDSPOSTGRESDB_HOST or RDSPOSTGRESDB_PORT environment variables are not set!")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': rds_postgres_db_name,
        'USER': rds_postgres_db_user,
        'PASSWORD': rds_postgres_db_password,
        'HOST': rds_postgres_db_host,
        'PORT': rds_postgres_db_port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



## S3 settings 
# https://django-storages.readthedocs.io/en/stable/backends/amazon-S3.html
import socket
S3_BUCKET_NAME = 'taxjimmystorage'
if not 'vpn.private.upenn.edu' in socket.gethostname(): # Only use S3 for non-VPN connections
    # S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME', None)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": S3_BUCKET_NAME,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": S3_BUCKET_NAME,
                "location": "static"  # This will create a 'static' prefix for static files
            },
        }
    }




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Penn colors
PENN_COLORS = {
    'PENN_RED': '#990000',
    'PENN_BLUE': '#011F5B',
    'PENN_GRAY': '#707070',
}

# For debug toolbar
INTERNAL_IPS = [
    '127.0.0.1',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}



# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# cognito
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]
# cognito
SOCIALACCOUNT_PROVIDERS = {
    'amazon_cognito': {
        'DOMAIN': 'https://taxjimmy.auth.us-east-1.amazoncognito.com',
        'REDIRECT_URI': 'http://localhost:8000/accounts/amazon-cognito/login/callback/',
    }
}
SITE_ID = 3  # For 127.0.0.1:8000
ACCOUNT_EMAIL_VERIFICATION = "none"  # cognit
LOGIN_REDIRECT_URL = "/"  # cognito
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Allauth settings
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Add this to your settings.py

# Function to detect if we're running in Lambda
def is_running_in_lambda():
    return bool(os.getenv('AWS_LAMBDA_FUNCTION_NAME'))

# Update the LOGGING configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'utils': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'taxright': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        }
    }
}

# AWS Settings
AWS_REGION = 'us-east-1'


# Email settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# For development/testing - if using console backend
if EMAIL_BACKEND == 'django.core.mail.backends.console.EmailBackend':
    EMAIL_HOST = None
    EMAIL_PORT = None
    EMAIL_HOST_USER = None
    EMAIL_HOST_PASSWORD = None
    EMAIL_USE_TLS = False
else:
    # Production email settings
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'



# Chroniker Settings
CHRONIKER_SETTINGS = {
    'process_method': 'process',  # Switch back to process-based execution
    'use_subprocess': True,      # Use subprocess for better isolation
}

CHRONIKER_DISABLE_RAW_COMMAND = True
CHRONIKER_EMAIL_SENDER = DEFAULT_FROM_EMAIL
CHRONIKER_EMAIL_SUCCESS_RECIPIENTS = []
CHRONIKER_EMAIL_FAILURE_RECIPIENTS = []
CHRONIKER_ALLOW_PARALLEL_RUNS = False




